### PR TITLE
[WIP]: Refactor package

### PR DESCRIPTION
**Pull request by kjappelbaum**
Hi Aditi 👋🏼

thanks for the great work --- really useful 👍🏼
I'm building a package in which I wanted to use your code. For this, however, i needed it to be pip installable from PyPi/Conda and a slightly cleaner way to call methods. 

For this reason, I started to refactor your package. I realize that a lot of the changes are opinionated --- this is the reason I am opening a draft PR. 

Some of the relevant changes: 
- switch to `src` layout
- renaming to `moltda` (for easier/more consistent imports). Of course, one can stick to `molecule-tda`. However, I find that hyphens in package names often lead to a lot of unnecessary problems in Python
- using `click` for the cli 
- some linting/formatting (`black`, `isort`, ...) 
- started adding some of the basics for docs, contribution guide, ... 
- started adding GH actions
- started adding type annotations 

#### Todo @kjappelbaum

- [ ] Make a conda recipe (other wise dependencies such as `cgalz` are too much of a headache

### CODE REVIEW

**Comment by a1k12** [comment]
Hi Kevin, these all look like useful changes (I'm taking a closer look now)! I also just updated the dependencies; it should be straightforward to create a virtual env from either the poetry files or the .txt file: I had no issues with cgal installations this way.

**Comment by kjappelbaum** [comment]
>My real question was about how CubicSupercellTransformation works, but that's probably best directed to the pymatgen folks.

ah - yes this just attempts to replicate the cell in such a way that you get a as-much-as cubic cell with some minimum size (the code is quite simple: https://github.com/materialsproject/pymatgen/blob/1b6d1d2212dcf3a559cb2c489dd25e9754f9f788/pymatgen/transformations/advanced_transformations.py#L1493-L1626)

>The answer you get for one periodic supercell can have a non-trivial relationship to answers you'd get for i*j*k copies of this cell. 

yep, wanted to compare how the similarity of some crystalline materials change under this metric

**Comment by mrzv** [comment]
Thanks. I'll take a look at their code.

Oh, and please share what you find out about the similarity changing. It's something I'm interested in.

**Comment by kjappelbaum** [comment]
>Oh, and please share what you find out about the similarity changing. It's something I'm interested in.

will keep you posted!

**Comment by mrzv** [comment]
> BTW, i think the license should rather be GPL (due to diode)?

It's not that simple. I believe the current interpretation (that was a surprise to me, but it seems most of the world has accepted) is that just because a code uses a GPL code, it doesn't have to be GPL itself. The end-user is bound by GPL, since they are using both, but the code itself can be freely licensed. (I suppose one could write a free version of `diode` and use it as a drop-in replacement.)

In any case, this code's release was reviewed by our licensing people, who were made aware of diode's license.

**Comment by kjappelbaum** [comment]
@a1k12 one question we should resolve is the naming. For a python package we should remove the dash (https://peps.python.org/pep-0008/#descriptive-naming-styles). We could replace it with an underscore (`mol_tda`, which would, however, make it inconsistent with conda where they encourage dashes ...) or with a contraction of the two words (e.g. `moleculetda`, `moltda`). 

What are your thought on this?

**Comment by a1k12** [comment]
@kjappelbaum I agree, I'm happy to change it to `moleculetda`.

**Comment by kjappelbaum** [comment]
Thanks for the feedback, renamed it. I looked through the changeset of this PR and nothing seemed unreasonable to me (except for the `periodic` keyword arguments that are turned off by default --- happy to remove them). 

The tests right now are quite basic, happy to add more. 

Also, the docs are relatively basic in the default theme, also happy to work on them later (perhaps after the first batch is merged and the docs deployed)

**Comment by a1k12** [comment]
Had to make sure the dependencies conflict was resolved, looks good to me.

**Pull request merged**
