### PR TITLE
make docs and build work

### PR DESCRIPTION
**Pull request by kjappelbaum**
making the last changes such that one can have some basic docs on readthedocs or github pages and that the `tox -e finish` can be used by one of us to push the thing to PyPi.

### CODE REVIEW

**Comment by kjappelbaum** [comment]
i chose the furo theme for docs, at the moment only includes the basic api docs. 

Screen Shot 2022-08-06 at 18 19 04

**Comment by kjappelbaum** [comment]
so, `bump2version` seems to work, as does the build. 

For adding it to PyPi we have the following options: 

1. I do it and add you as an admin 
2. You do it yourself ;)

**Comment by kjappelbaum** [comment]
i also tweaked the main GH action to no longer fail

**Comment by a1k12** [comment]
Looks good, thanks!

**Comment by kjappelbaum** [comment]
@a1k12 thanks! Do you want me to push it to PyPi or do you want to give it a shot yourself?

**Comment by a1k12** [comment]
Should be pushed to PyPi now!

**Pull request merged**
